# Generated by Django 4.2.30 on 2026-06-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_purchase_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reset_token',
        ),
        migrations.AddField(
            model_name='purchase',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
